var GALLERY_DATA = [
  {
    "id": "j16",
    "player": "Henrik Sedin",
    "title": "'2011 Stanley Cup Final' Wordmark Orca Home Blue",
    "team": "Vancouver Canucks",
    "number": "33",
    "designation": "C",
    "year": "2011",
    "size": "58",
    "manufacturer": "Reebok",
    "model": "Edge 2.0 Vector",
    "country": "Made in Canada",
    "patch1": "2011 Stanley Cup Final",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$414.39",
    "images": [
      "images/IMG_2771.jpg",
      "images/IMG_2774.jpg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j09",
    "player": "Markus Naslund",
    "title": "'West Coast Express' Orca Home Navy",
    "team": "Vancouver Canucks",
    "number": "19",
    "designation": "C",
    "year": "2005–2007",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "6100",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$313.76",
    "images": [
      "images/IMG_2706.jpeg",
      "images/IMG_2708.jpeg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j01",
    "player": "Trevor Linden",
    "title": "'Flying Skate' Away Black",
    "team": "Vancouver Canucks",
    "number": "16",
    "designation": "C",
    "year": "1992–1997",
    "size": "54",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$502.29",
    "images": [
      "images/IMG_2713.jpeg",
      "images/IMG_2714.jpeg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j39",
    "player": "JT Miller",
    "title": "'Sprite Can' Reverse Retro 1.0 Alt Gradient",
    "team": "Vancouver Canucks",
    "number": "9",
    "designation": "Blank",
    "year": "2020–2021",
    "size": "56",
    "manufacturer": "Adidas",
    "model": "ADIZERO",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "800",
    "images": [
      "images/IMG_2740.jpeg",
      "images/IMG_2734.jpeg"
    ],
    "jerseyType": "Game Worn",
    "condition": "New with Tags",
    "category": "canucks"
  },
  {
    "id": "j14",
    "player": "Stan Smyl",
    "title": "'Flying V' Vintage Program Home Yellow",
    "team": "Vancouver Canucks",
    "number": "12",
    "designation": "C",
    "year": "1982–1985 Remake",
    "size": "56",
    "manufacturer": "CCM",
    "model": "6100",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$385.43",
    "images": [
      "images/IMG_2716.jpeg",
      "images/IMG_2717.jpeg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "Very Good",
    "category": "canucks"
  },
  {
    "id": "j12",
    "player": "Markus Naslund",
    "title": "'Stick in Rink' Vintage Program Alt Blue",
    "team": "Vancouver Canucks",
    "number": "19",
    "designation": "C",
    "year": "2003/2004",
    "size": "56",
    "manufacturer": "CCM",
    "model": "6100",
    "country": "Made in Canada",
    "patch1": "NHL Vintage Program",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$282.93",
    "images": [
      "images/IMG_2730.jpeg",
      "images/IMG_2725.jpeg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "New with Tags",
    "category": "canucks"
  },
  {
    "id": "j28",
    "player": "Sidney Crosby",
    "title": "'Golden Goal' Vancouver 2010 Olympics Away White",
    "team": "Team Canada",
    "number": "87",
    "designation": "Blank",
    "year": "2010",
    "size": "56",
    "manufacturer": "Nike",
    "model": "Swift",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "644.5",
    "images": [
      "images/IMG_2765.jpg",
      "images/IMG_2766.jpg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "New without Tags",
    "category": ""
  },
  {
    "id": "j30",
    "player": "Sidney Crosby",
    "title": "Vancouver 2010 Olympics Home Red",
    "team": "Team Canada",
    "number": "87",
    "designation": "Blank",
    "year": "2010",
    "size": "54",
    "manufacturer": "Nike",
    "model": "Swift",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$408.62",
    "images": [
      "images/IMG_2767.jpg",
      "images/IMG_2768.jpg"
    ],
    "jerseyType": "Retail On-Ice",
    "condition": "New with Tags",
    "category": "canada"
  },
  {
    "id": "j29",
    "player": "Roberto Luongo",
    "title": "Vancouver 2010 Olympics Away White",
    "team": "Team Canada",
    "number": "1",
    "designation": "Blank",
    "year": "2010",
    "size": "58 Goalie Cut",
    "manufacturer": "Nike",
    "model": "Swift",
    "country": "Made in Canada",
    "patch1": "Hockey Canada Chest Crest",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$556.00",
    "images": [
      "images/PXL_20260424_1858088452.jpg",
      "images/PXL_20260424_1857132262.jpg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canada"
  },
  {
    "id": "j27",
    "player": "Quinn Hughes",
    "title": "'Flying Skate' Alt Black",
    "team": "Vancouver Canucks",
    "number": "43",
    "designation": "C",
    "year": "2023/2024",
    "size": "56",
    "manufacturer": "Adidas",
    "model": "Primegreen",
    "country": "Made in Canada",
    "patch1": "TD Sponsor",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$405.10",
    "images": [
      "images/IMG_2744.jpeg",
      "images/IMG_2756.jpeg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j26",
    "player": "Quinn Hughes",
    "title": "Modern Orca Home Blue",
    "team": "Vancouver Canucks",
    "number": "43",
    "designation": "C",
    "year": "2023/2024",
    "size": "54",
    "manufacturer": "Adidas",
    "model": "Primegreen",
    "country": "Made in Canada",
    "patch1": "TD Sponsor",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$311.93",
    "images": [
      "images/IMG_2759.jpeg",
      "images/IMG_2750.jpeg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j13",
    "player": "Markus Naslund",
    "title": "'Stick in Rink' Vintage Program Alt White",
    "team": "Vancouver Canucks",
    "number": "19",
    "designation": "C",
    "year": "2003/2004",
    "size": "56",
    "manufacturer": "CCM",
    "model": "6100",
    "country": "Made in Canada",
    "patch1": "NHL Vintage Program",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$247.00",
    "images": [
      "images/IMG_2719.jpeg",
      "images/IMG_2722.jpeg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "id": "j10",
    "player": "Markus Naslund",
    "title": "'West Coast Express' Orca Away White",
    "team": "Vancouver Canucks",
    "number": "19",
    "designation": "C",
    "year": "2005–2007",
    "size": "54",
    "manufacturer": "Reebok",
    "model": "6100 Airknit",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$336.42",
    "images": [
      "images/IMG_2709.jpeg",
      "images/IMG_2711.jpeg"
    ],
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "category": "canucks"
  },
  {
    "category": "other",
    "team": "New York Knicks",
    "title": "'2026 NBA Finals' Icon Blue",
    "player": "Jalen Brunson",
    "number": "11",
    "designation": "Blank",
    "manufacturer": "Nike",
    "model": "Dri-Fit ADV",
    "year": "2026",
    "size": "52",
    "country": "Made in Thailand",
    "jerseyType": "Retail On-Court",
    "condition": "New with Tags",
    "cost": "174.8",
    "patch1": "Visit Abu Dhabi Sponsor",
    "patch2": "Finals Chromaflex PVC",
    "patch3": "USA 250 PVC",
    "images": [],
    "id": "pmqj4l8fsl3sv4",
    "status": "Public"
  },
  {
    "category": "other",
    "team": "New York Knicks",
    "title": "'2026 NBA Finals' Association White",
    "player": "Jalen Brunson",
    "number": "11",
    "designation": "Blank",
    "manufacturer": "Nike",
    "model": "Dri-Fit ADV",
    "year": "2026",
    "size": "56",
    "country": "Made in Thailand",
    "jerseyType": "Retail On-Court",
    "condition": "New with Tags",
    "cost": "231.79",
    "patch1": "Visit Abu Dhabi Sponsor",
    "patch2": "NBA Finals Chromoflex PVC",
    "patch3": "USA 250 PVC",
    "images": [],
    "id": "pmqj4oy96qgtep",
    "status": "Public"
  },
  {
    "category": "canucks",
    "team": "Vancouver Canucks",
    "title": "'50th Anniversary' Home Orca Blue",
    "player": "Quinn Hughes",
    "number": "43",
    "designation": "Blank",
    "manufacturer": "Adidas",
    "model": "ADIZERO",
    "year": "2019-2020",
    "size": "56",
    "country": "Made in Canada",
    "jerseyType": "Team Issued",
    "condition": "New without Tags",
    "cost": "253.33",
    "patch1": "50th Anniversary Patch",
    "patch2": "",
    "patch3": "",
    "images": [],
    "id": "pmqikc8rkcpx7n",
    "status": "Public"
  },
  {
    "category": "canucks",
    "team": "Vancouver Canucks",
    "title": "'West Coast Express' Orca Home White",
    "player": "Markus Naslund",
    "number": "19",
    "designation": "C",
    "manufacturer": "CCM",
    "model": "6100 Ultrafil",
    "year": "2003/2004",
    "size": "54",
    "country": "Made in Canada",
    "jerseyType": "Retail On-Ice",
    "condition": "Very Good",
    "cost": "175.82",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "images": [],
    "id": "pmqilg82gj27hs",
    "status": "Public"
  },
  {
    "id": "j02",
    "player": "Trevor Linden",
    "title": "'Flying Skate' Home White",
    "team": "Vancouver Canucks",
    "number": "16",
    "designation": "Blank",
    "year": "1992–1995",
    "size": "52",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$333.00",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j04",
    "player": "Pavel Bure",
    "title": "'Flying Skate' Away Black",
    "team": "Vancouver Canucks",
    "number": "96",
    "designation": "A",
    "year": "1995–1997",
    "size": "52",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$221.45",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j05",
    "player": "Pavel Bure",
    "title": "'Orca' Away Navy",
    "team": "Vancouver Canucks",
    "number": "10",
    "designation": "Blank",
    "year": "1997–1998",
    "size": "54",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "1998 Vancouver All-Star Game",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$236.29",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j06",
    "player": "Pavel Bure",
    "title": "'Orca' Home White",
    "team": "Vancouver Canucks",
    "number": "10",
    "designation": "A",
    "year": "1997–1998",
    "size": "54",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "1998 Vancouver All-Star Game",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$366.67",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j08",
    "player": "Trevor Linden",
    "title": "'West Coast Express' Orca Away Navy",
    "team": "Vancouver Canucks",
    "number": "16",
    "designation": "A",
    "year": "2001–2003",
    "size": "56",
    "manufacturer": "CCM",
    "model": "Ultrafil",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$184.44",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j03",
    "player": "Pavel Bure",
    "title": "'Flying Skate' Home Away",
    "team": "Vancouver Canucks",
    "number": "10",
    "designation": "Blank",
    "year": "1992–1995",
    "size": "56",
    "manufacturer": "CCM",
    "model": "Big Block",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$400.00",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j11",
    "player": "Markus Naslund",
    "title": "'Salmon Gradient' Orca Alt",
    "team": "Vancouver Canucks",
    "number": "19",
    "designation": "C",
    "year": "2002–2005",
    "size": "56",
    "manufacturer": "CCM",
    "model": "6100",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$337.42",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New with Tags"
  },
  {
    "id": "j15",
    "player": "Trevor Linden",
    "title": "'Wordmark' Home Blue",
    "team": "Vancouver Canucks",
    "number": "16",
    "designation": "A",
    "year": "2007",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "Edge 1.0",
    "country": "Made in Canada",
    "patch1": "",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$269.65",
    "images": [],
    "jerseyType": "Retail On-Ice",
    "category": "canucks",
    "condition": "New with Tags"
  },
  {
    "id": "j17",
    "player": "Henrik Sedin",
    "title": "'2011 Stanley Cup Final' Wordmark Orca Home Blue",
    "team": "Vancouver Canucks",
    "number": "33",
    "designation": "C",
    "year": "2011",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "Edge 2.0 Vector",
    "country": "Made in Canada",
    "patch1": "2011 Stanley Cup Final",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$194.91",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j18",
    "player": "Daniel Sedin",
    "title": "'2011 Stanley Cup Final' Wordmark Orca Away White",
    "team": "Vancouver Canucks",
    "number": "22",
    "designation": "A",
    "year": "2011",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "Edge 2.0 Vector",
    "country": "Made in Canada",
    "patch1": "2011 Stanley Cup Final",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$251.69",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "Very Good"
  },
  {
    "id": "j19",
    "player": "Henrik Sedin",
    "title": "'Centennial' Wordmark Orca Away White",
    "team": "Vancouver Canucks",
    "number": "33",
    "designation": "Blank",
    "year": "2017",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "Edge 2.0 Wordmark",
    "country": "Made in Canada",
    "patch1": "NHL 100",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "320.86",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New with Tags"
  },
  {
    "id": "j20",
    "player": "Henrik Sedin",
    "title": "'Modern Stick in Rink' Alt Blue",
    "team": "Vancouver Canucks",
    "number": "33",
    "designation": "C",
    "year": "2013",
    "size": "56",
    "manufacturer": "Reebok",
    "model": "Edge 2.0 Wordmark",
    "country": "Made in Canada",
    "patch1": "V Patch",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$423.91",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j22",
    "player": "Quinn Hughes",
    "title": "'50th Anniversary' Orca Away White",
    "team": "Vancouver Canucks",
    "number": "43",
    "designation": "Blank",
    "year": "2019/2020",
    "size": "56",
    "manufacturer": "Adidas",
    "model": "ADIZERO",
    "country": "Made in Canada",
    "patch1": "50th Anniversary",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$205.35",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j23",
    "player": "Elias Petterson",
    "title": "'50th Anniversary' Stick in Rink Heritage Blue",
    "team": "Vancouver Canucks",
    "number": "40",
    "designation": "Blank",
    "year": "2019/2020",
    "size": "56",
    "manufacturer": "Adidas",
    "model": "ADIZERO",
    "country": "Made in Canada",
    "patch1": "50th Anniversary",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$371.29",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j24",
    "player": "Elias Petterson",
    "title": "'50th Anniversary' Throwback Skate Black",
    "team": "Vancouver Canucks",
    "number": "40",
    "designation": "Blank",
    "year": "2019/2020",
    "size": "56",
    "manufacturer": "Adidas",
    "model": "ADIZERO",
    "country": "Made in Canada",
    "patch1": "50th Anniversary",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$483.34",
    "images": [],
    "jerseyType": "Team Issued",
    "category": "canucks",
    "condition": "New without Tags"
  },
  {
    "id": "j31",
    "player": "Henrik Sedin",
    "title": "'40th anniversary' Stick-in-Rink Alt White",
    "team": "Vancouver Canucks",
    "number": "33",
    "designation": "C",
    "year": "2010/2011",
    "size": "",
    "manufacturer": "Reebok",
    "model": "Retail Edge Vector",
    "country": "Made in Indonesia",
    "patch1": "40th Anniversary",
    "patch2": "",
    "patch3": "",
    "status": "Public",
    "cost": "$221.81",
    "images": [],
    "jerseyType": "Replica/Indo Authentic",
    "category": "canucks",
    "condition": "Very Good"
  }
];